//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryLeakSample.Client.Local_MemoryLeakSample {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Local_MemoryLeakSample.LeakServiceSoap")]
    public interface LeakServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LongRequest", ReplyAction="*")]
        void LongRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LongRequest", ReplyAction="*")]
        System.Threading.Tasks.Task LongRequestAsync();
        
        // CODEGEN: Generating message contract since element name SendEmailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse SendEmail(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse> SendEmailAsync(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
        public MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequestBody Body;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendEmailRequestBody {
        
        public SendEmailRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponseBody Body;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmailResult;
        
        public SendEmailResponseBody() {
        }
        
        public SendEmailResponseBody(string SendEmailResult) {
            this.SendEmailResult = SendEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LeakServiceSoapChannel : MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeakServiceSoapClient : System.ServiceModel.ClientBase<MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap>, MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap {
        
        public LeakServiceSoapClient() {
        }
        
        public LeakServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeakServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeakServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeakServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LongRequest() {
            base.Channel.LongRequest();
        }
        
        public System.Threading.Tasks.Task LongRequestAsync() {
            return base.Channel.LongRequestAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap.SendEmail(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public string SendEmail() {
            MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest inValue = new MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest();
            inValue.Body = new MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequestBody();
            MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse retVal = ((MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap)(this)).SendEmail(inValue);
            return retVal.Body.SendEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse> MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap.SendEmailAsync(MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailResponse> SendEmailAsync() {
            MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest inValue = new MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequest();
            inValue.Body = new MemoryLeakSample.Client.Local_MemoryLeakSample.SendEmailRequestBody();
            return ((MemoryLeakSample.Client.Local_MemoryLeakSample.LeakServiceSoap)(this)).SendEmailAsync(inValue);
        }
    }
}
